name: ir_bluebank_card
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flip_card: ^0.7.0
  gap: ^3.0.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/blue-logo.png
    - assets/images/cheap.png
    - assets/images/saman-bank.png
    - assets/images/checked.png
    - assets/fonts/Yekan.ttf
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: yekan
      fonts:
        - asset: assets/fonts/Yekan.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700